extends SceneTree

const OdometerScript = preload("res://scripts/runtime/vehicle/runtime_odometer.gd")
const PanelScript = preload("res://scripts/runtime/ui/runtime_odometer_panel.gd")


func _initialize() -> void:
	call_deferred("_run")


func _run() -> void:
	var town_directory := ProjectSettings.globalize_path("res://tools/tests/output/odometer_test_%d" % OS.get_process_id())
	var save_directory := town_directory.path_join("saves")
	var save_path := save_directory.path_join("vehicle_odometer.json")
	var meter = OdometerScript.new()
	assert(meter.load_for_town(town_directory).ok, "A new town odometer should start without a save file.")
	meter.record_world_displacement(Vector2.ZERO, Vector2(200, 0), 2.0)
	meter.record_world_displacement(Vector2(800, 0), Vector2.ZERO, 8.0)
	meter.record_world_displacement(Vector2.ZERO, Vector2.ZERO, 2.0)
	assert(is_equal_approx(meter.total_metres, 200.0) and is_equal_approx(meter.trip_metres, 200.0), "Map-scale and reverse distance were not counted correctly.")
	assert(meter.save().ok and FileAccess.file_exists(save_path), "Mileage did not save beside the town project.")
	var reopened = OdometerScript.new()
	assert(reopened.load_for_town(town_directory).ok, "Saved mileage did not reload.")
	assert(is_equal_approx(reopened.total_metres, 200.0) and is_equal_approx(reopened.trip_metres, 200.0), "Loaded values changed.")
	var panel = PanelScript.new()
	root.add_child(panel)
	panel.set_display_state(false, false)
	assert(not panel.visible, "The odometer must be hidden on foot.")
	panel.set_display_state(true, false)
	assert(panel.visible and is_equal_approx(panel.position.y, 140.0), "The odometer must appear while driving.")
	panel.set_display_state(true, true)
	assert(panel.visible and is_equal_approx(panel.position.y, 40.0), "The odometer must remain available in the map when seated in the car.")
	panel.set_display_state(false, true)
	assert(not panel.visible, "The map must not reveal the odometer on foot.")
	assert(panel.RESET_RECT.end.x < panel.size.x and panel.RESET_RECT.end.y < panel.size.y, "The reset area overlaps the odometer panel border.")
	panel.trip_reset_requested.connect(func() -> void: reopened.reset_trip())
	var click := InputEventMouseButton.new()
	click.button_index = MOUSE_BUTTON_LEFT
	click.pressed = true
	click.position = Vector2(20, 25)
	panel._gui_input(click)
	assert(is_equal_approx(reopened.trip_metres, 200.0), "A click outside Reset unexpectedly erased the trip.")
	click.position = Vector2(180, 25)
	panel._gui_input(click)
	assert(is_zero_approx(reopened.trip_metres) and is_equal_approx(reopened.total_metres, 200.0), "Reset affected the lifetime odometer or missed the trip.")
	var after_reset = OdometerScript.new()
	assert(after_reset.load_for_town(town_directory).ok, "Trip reset was not saved immediately.")
	assert(is_zero_approx(after_reset.trip_metres) and is_equal_approx(after_reset.total_metres, 200.0), "Reset did not persist.")
	after_reset.record_world_displacement(Vector2.ZERO, Vector2(2, 0), 2.0)
	assert(after_reset.save().ok, "A later save could not refresh the odometer backup.")
	var damaged_file := FileAccess.open(save_path, FileAccess.WRITE)
	damaged_file.store_string("incomplete save")
	damaged_file.close()
	var recovered = OdometerScript.new()
	var recovery_result: Dictionary = recovered.load_for_town(town_directory)
	assert(recovery_result.ok and recovered.recovered_from_backup, "The previous odometer copy did not protect an incomplete save.")
	assert(is_equal_approx(recovered.total_metres, 200.0), "Backup recovery changed the lifetime odometer.")
	assert(recovered.reset_trip().ok, "Recovered mileage could not be saved again.")
	panel.free()
	DirAccess.remove_absolute(save_path)
	DirAccess.remove_absolute(save_path + ".bak")
	DirAccess.remove_absolute(save_directory)
	DirAccess.remove_absolute(town_directory)
	print("RUNTIME ODOMETER PASSED: real movement, map scales, reverse, save/reopen and anytime trip reset.")
	quit(0)
