'use strict';
const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const {validateNpcCreations, imageDimensions} = require('../npc_creations/validate-npc-creations');
const temporary = fs.mkdtempSync(path.join(os.tmpdir(),'world-twin-npc-creations-'));
const relative = 'assets/npcs/custom/mentor/front.png';
fs.mkdirSync(path.dirname(path.join(temporary,relative)),{recursive:true});
const source = path.resolve(__dirname,'../../assets/actors/custom/morpheus_v16.png');
fs.copyFileSync(source,path.join(temporary,relative));
const base = {schema_version:1,kind:'npc_creations',creations:[{id:'mentor',name:'Mentor',gender:'man',age_group:'adult',skin_tone_group:'dark',seat_anchor_y:.58,poses:{idle:{front:[relative]},walk:{left:[relative,relative]},sit:{front:[relative]}}}]};
const placement = {id:'npc_1',display_name:'Guide',actor_kind:'npc',appearance:{mode:'custom_creation',template_id:'mentor',npc_asset:'creation_mentor',gender:'man',age_group:'adult',skin_tone_group:'dark'}};
let checks = 0;
function check(value, expected, message) { assert.strictEqual(value,expected,message); checks++; }
function reject(change) { const changed = structuredClone(base); change(changed); check(validateNpcCreations(changed,temporary).ok,false); }
check(validateNpcCreations(base,temporary,[placement]).ok,true,'Valid artwork/reference rejected');
check(validateNpcCreations({schema_version:1,kind:'npc_creations',creations:[]}).ok,true);
check(validateNpcCreations(null).ok,false);
reject(data=>data.schema_version=2);
reject(data=>data.creations={});
reject(data=>data.creations=Array(101).fill(data.creations[0]));
reject(data=>data.creations.push(structuredClone(data.creations[0])));
for (const id of ['npc_reserved','../escape','UPPER',1,'']) reject(data=>data.creations[0].id=id);
for (const name of ['', '  ', 'x'.repeat(81), null]) reject(data=>data.creations[0].name=name);
reject(data=>data.creations[0].gender='unsupported');
reject(data=>data.creations[0].age_group='child');
reject(data=>data.creations[0].skin_tone_group='automatic');
for (const anchor of [.34,.76,Infinity,'0.58']) reject(data=>data.creations[0].seat_anchor_y=anchor);
reject(data=>data.creations[0].poses=[]);
reject(data=>data.creations[0].poses.idle={front:[]});
reject(data=>data.creations[0].poses.walk.left=Array(9).fill(relative));
reject(data=>data.creations[0].poses.walk.left=relative);
reject(data=>data.creations[0].poses.jump={front:[relative]});
reject(data=>data.creations[0].poses.sit.bottom=[relative]);
for (const invalidPath of ['../outside.png','assets/npcs/../escape.png','assets/npcs/evil.gd','assets/npcs\\front.png',true]) reject(data=>data.creations[0].poses.idle.front=[invalidPath]);
reject(data=>data.creations[0].poses.idle.front=['assets/npcs/missing.png']);
const morpheus={schema_version:1,kind:'npc_creations',creations:[{id:'morpheus',name:'My mentor',gender:'man',age_group:'adult',skin_tone_group:'dark',poses:{}}]};
check(validateNpcCreations(morpheus,temporary).ok,true,'Bundled Morpheus/rename rejected');
const bundledPlacement=structuredClone(placement); bundledPlacement.appearance.template_id='morpheus'; bundledPlacement.appearance.npc_asset='creation_morpheus';
check(validateNpcCreations({schema_version:1,kind:'npc_creations',creations:[]},temporary,[bundledPlacement]).ok,true,'Bundled default reference rejected');
const missing=structuredClone(placement); missing.appearance.template_id='missing'; missing.appearance.npc_asset='creation_missing';
check(validateNpcCreations(base,temporary,[missing]).ok,false);
for (const field of ['gender','age_group','skin_tone_group']) { const changed=structuredClone(placement); changed.appearance[field]='wrong'; check(validateNpcCreations(base,temporary,[changed]).ok,false); }
const incorrectAsset=structuredClone(placement); incorrectAsset.appearance.npc_asset='creation_other';
check(validateNpcCreations(base,temporary,{npcs:[incorrectAsset]}).ok,false);
const built={actor_kind:'npc',appearance:{mode:'built_in',npc_asset:'npc_light_woman_older',gender:'woman',age_group:'older',skin_tone_group:'light'}};
check(validateNpcCreations(base,temporary,[built]).ok,true);
built.appearance.npc_asset='npc_dark_man_young'; check(validateNpcCreations(base,temporary,[built]).ok,false);
check(validateNpcCreations(base,temporary,[{actor_kind:'npr',appearance:{mode:'random_static_asset',npc_asset:'npr'}}]).ok,true);
check(validateNpcCreations(base,temporary,[{actor_kind:'npr',appearance:{mode:'custom_creation',npc_asset:'npr'}}]).ok,false);
check(validateNpcCreations(base,temporary,{}).ok,false);
check(validateNpcCreations(base,temporary,[null]).ok,false);
// Negative image fixtures remain in this disposable OS-temp directory only.
const realBytes=fs.readFileSync(path.join(temporary,relative));
const tooWide=Buffer.from(realBytes); tooWide.writeUInt32BE(4097,16); fs.writeFileSync(path.join(temporary,relative),tooWide);
check(validateNpcCreations(base,temporary).ok,false,'Oversized image accepted');
fs.writeFileSync(path.join(temporary,relative),'not an image'); check(validateNpcCreations(base,temporary).ok,false,'Invalid image header accepted');
const huge=Buffer.alloc(20*1024*1024+1); realBytes.copy(huge); fs.writeFileSync(path.join(temporary,relative),huge); check(validateNpcCreations(base,temporary).ok,false,'20 MB image budget ignored');
fs.writeFileSync(path.join(temporary,relative),realBytes);
check(imageDimensions(realBytes,'.png')[0]>0,true);
const webp=Buffer.alloc(30); webp.write('RIFF',0); webp.write('WEBP',8); webp.write('VP8X',12); webp.writeUIntLE(63,24,3); webp.writeUIntLE(31,27,3);
check(JSON.stringify(imageDimensions(webp,'.webp')),JSON.stringify([64,32]));
const jpeg=Buffer.from([0xff,0xd8,0xff,0xc0,0,17,8,0,32,0,64,3,1,0x11,0,2,0x11,0,3,0x11,0]);
check(JSON.stringify(imageDimensions(jpeg,'.jpeg')),JSON.stringify([64,32]));
JSON.parse(fs.readFileSync(path.resolve(__dirname,'../../schemas/npc_creations.schema.json'),'utf8')); checks++;
console.log(JSON.stringify({passed:true,checks,temporary_directory:temporary}));
