extends SceneTree

const Store = preload("res://scripts/npcs/traders/trader_store.gd")
const Service = preload("res://scripts/npcs/traders/trade_service.gd")
const Inventory = preload("res://scripts/runtime/inventory/runtime_player_inventory.gd")
const Catalog = preload("res://scripts/inventory/item_catalog_store.gd")
const Editor = preload("res://scripts/npcs/traders/trader_editor.gd")
const Shop = preload("res://scripts/npcs/traders/runtime_shop.gd")
const Dialogue = preload("res://scripts/npcs/ollama_dialogue_client.gd")
const Personas = preload("res://scripts/npcs/persona_store.gd")
const Runtime = preload("res://scripts/runtime/town_runtime.gd")
const Population = preload("res://scripts/runtime/runtime_population.gd")
const Player = preload("res://scripts/runtime/runtime_player_character.gd")
const Stats = preload("res://scripts/runtime/inventory/runtime_player_stats.gd")
const Conversation = preload("res://scripts/npcs/runtime_conversation_layer.gd")
const Storyline = preload("res://scripts/npcs/storyline_npc_store.gd")
var accepted_count := 0

func _initialize() -> void:
	call_deferred("_run")

func _run() -> void:
	var directory := ProjectSettings.globalize_path("res://tools/tests/output/traders_%d" % OS.get_process_id())
	var catalog := Catalog.default_data()
	var inventory := Inventory.new()
	assert(inventory.load_for_town(directory, true, catalog).ok)
	var profile := {"enabled": true, "trade_role": "Barkeep", "persona_id": "trader_barkeep", "offers": [{"item_id": "beer", "stock": 20, "price_keks": 5}]}
	var quote := Service.quote(inventory, "moe", profile, catalog, "beer", 2)
	assert(quote.ok and quote.total == 10)
	assert(inventory.quantity("keks") == 100 and inventory.quantity("beer") == 0 and inventory.trader_stock.is_empty(), "Quoting spent inventory.")
	assert(not Service.quote(inventory, "moe", profile, catalog, "beer", 1.5).ok)
	assert(not Service.quote(inventory, "moe", profile, catalog, "beer", -1).ok)
	assert(not Service.quote(inventory, "moe", profile, catalog, "beer", 100).ok)
	assert(not Service.quote(inventory, "moe", profile, catalog, "unknown", 1).ok)
	assert(not Service.quote(inventory, "moe", profile, catalog, "keks", 1).ok)
	var forged := quote.duplicate()
	forged.total = 0
	assert(not Service.purchase(inventory, profile, catalog, forged).ok)
	var changed_price := profile.duplicate(true)
	changed_price.offers[0].price_keks = 6
	assert(not Service.purchase(inventory, changed_price, catalog, quote).ok, "An old quote accepted a changed price.")
	assert(Service.purchase(inventory, profile, catalog, quote).ok)
	assert(inventory.quantity("keks") == 90 and inventory.quantity("beer") == 2)
	assert(Service.remaining(inventory, "moe", profile.offers[0]) == 18)
	assert(inventory.trader_stock.moe._keks_received == 10)
	var reload := Inventory.new()
	assert(reload.load_for_town(directory, true, catalog).ok)
	assert(reload.quantities == inventory.quantities and reload.trader_stock == inventory.trader_stock, "Both inventories did not reload together.")
	assert(Service.purchase(reload, profile, catalog, Service.quote(reload, "moe", profile, catalog, "beer", 1)).ok, "Atomic replacement failed on existing Windows save.")
	assert(not Service.quote(reload, "moe", profile, catalog, "beer", 18).ok, "Stock/funds checks failed.")
	var zero_funds := Inventory.new()
	zero_funds.quantities = {"keks": 0}
	assert(not Service.quote(zero_funds, "moe", profile, catalog, "beer", 1).ok)
	reload.saving_enabled = false
	var before := reload.quantities.duplicate(true)
	var before_stock := reload.trader_stock.duplicate(true)
	assert(not Service.purchase(reload, profile, catalog, Service.quote(reload, "moe", profile, catalog, "beer", 1)).ok)
	assert(before == reload.quantities and before_stock == reload.trader_stock, "Failed persistence did not roll back.")
	var placements := {"npcs": [{"id": "moe", "display_name": "Moe", "location": {"space": "interior", "building_id": "pub", "floor_id": "ground_floor"}}]}
	var data := {"schema_version": 1, "traders": {"moe": profile}}
	assert(Store.new().save_to_town(directory, data, placements, catalog, Personas.recommended_data()).ok)
	var editor := Editor.new()
	root.add_child(editor)
	editor.setup(directory, placements, Personas.recommended_data(), func(_location): return "The Pub / Ground floor")
	assert(editor.npc_choice.get_item_text(0).contains("The Pub / Ground floor"))
	editor.price_spin.value = 7
	editor.stock_spin.value = 12
	for i in editor.item_choice.item_count:
		if editor.item_choice.get_item_metadata(i) == "beer": editor.item_choice.select(i)
	editor._save_offer()
	assert(editor.save(Personas.recommended_data()).ok)
	assert(Store.new().load_from_town(directory).data.traders.moe.offers[0].price_keks == 7)
	editor._select_offer(0)
	editor.price_spin.value = 9
	assert(editor.save(Personas.recommended_data()).ok)
	assert(Store.new().load_from_town(directory).data.traders.moe.offers[0].price_keks == 9, "Top Save lost edited selected-item fields.")
	assert(Storyline._next_number({"npcs": [], "next_npc_number": 5}) == 5)
	assert(Storyline._next_number({"npcs": [{"id": "storyline_npc_004"}]}) == 5, "Deleted NPC IDs can be reused as traders.")
	var first_npc := Storyline.new().add_outdoor_npc(Storyline.empty_data(), {"latitude": -36.08, "longitude": 146.91}, "test", Personas.recommended_data())
	assert(first_npc.ok)
	assert(Storyline.new().save_to_town(directory, first_npc.data, {}, [], Personas.recommended_data()).ok)
	var deleted: Dictionary = first_npc.data.duplicate(true)
	deleted.npcs.clear()
	assert(Storyline.new().save_to_town(directory, deleted, {}, [], Personas.recommended_data()).ok)
	var reopened_placements := Storyline.new().load_from_town(directory, {}, [], Personas.recommended_data())
	var second_npc := Storyline.new().add_outdoor_npc(reopened_placements.data, {"latitude": -36.08, "longitude": 146.91}, "test", Personas.recommended_data())
	assert(second_npc.ok and second_npc.npc.id != first_npc.npc.id, "Deleting/reloading reused a saved trader identity.")
	var shop := Shop.new()
	root.add_child(shop)
	shop.bind_trader(inventory, catalog, directory, "moe", profile, "Moe")
	shop.trade_accepted.connect(func(_quote): accepted_count += 1)
	shop.propose("beer", 1)
	assert(shop.visible and not shop.pending.is_empty())
	shop.cancel_quote()
	shop._accept()
	assert(accepted_count == 0 and inventory.quantity("beer") == 2)
	shop.propose("beer", 1)
	shop._accept()
	shop._accept()
	assert(accepted_count == 1, "Double acceptance emitted duplicate event.")
	var adapter := Dialogue.new()
	root.add_child(adapter)
	adapter.structured_trade = true
	adapter.accumulated_reply = JSON.stringify({"reply": "A beer? Certainly!", "item_id": "beer", "quantity": 1})
	adapter._finish_reply()
	assert(adapter.purchase_suggestion == {"item_id": "beer", "quantity": 1})
	assert(inventory.quantity("beer") == 2, "Model response changed gameplay state.")
	adapter.purchase_suggestion = {}
	adapter.accumulated_reply = JSON.stringify({"reply": "Hello!", "item_id": "beer", "quantity": 1.2})
	adapter._finish_reply()
	assert(adapter.purchase_suggestion.is_empty())
	var request := adapter.ask(Store.presets()[0], "One beer please", [], {"endpoint": "http://127.0.0.1:11434", "model": "test"}, "", Store.presets(), Service.context(inventory, "moe", profile, catalog))
	assert(request.ok)
	var payload: Dictionary = JSON.parse_string(adapter.request_body)
	assert(payload.format.properties.quantity.maximum == 99 and payload.format.required == ["reply", "item_id", "quantity"] and payload.options.num_predict == 128)
	adapter.cancel()
	var real_town := ProjectSettings.globalize_path("res://../Test Maps/albury/albury")
	var pub := Store.new().load_from_town(real_town)
	assert(pub.ok and pub.data.traders.storyline_npc_004.offers[0].item_id == "beer")
	# Exercise the real conversation -> quote -> Accept -> inventory event link,
	# without writing anything into the user's Albury saves.
	var runtime := Node2D.new()
	root.add_child(runtime)
	runtime.set_script(Runtime)
	runtime.set_process(false)
	runtime.set_process_unhandled_input(false)
	runtime.player_inventory = inventory
	runtime.item_catalog_data = catalog
	runtime.player_stats = Stats.new()
	runtime.town_directory = directory
	runtime.collision_data = {"runtime_scale": {"pixels_per_metre": 8.0}}
	runtime.persona_data = Personas.recommended_data()
	runtime.trader_data = pub.data
	runtime.player = Player.new()
	runtime.add_child(runtime.player)
	runtime.player.set_physics_process(false)
	runtime.player.position = Vector2(100,120)
	runtime.population = Population.new()
	runtime.add_child(runtime.population)
	runtime.population.set_process(false)
	runtime.population.visible = false
	runtime.population.set_active_interior("601183200", "ground_floor")
	runtime.population.agents.append({"kind": "person", "position": Vector2(100,100), "space": "interior", "building_id": "601183200", "floor_id": "ground_floor", "storyline_npc_id": "storyline_npc_004", "display_name": "Moe"})
	runtime.conversation_layer = Conversation.new()
	runtime.add_child(runtime.conversation_layer)
	runtime.camera = Camera2D.new()
	runtime.add_child(runtime.camera)
	runtime.dialogue_client = Dialogue.new()
	runtime.add_child(runtime.dialogue_client)
	runtime._build_hud()
	runtime._start_conversation()
	assert(runtime.conversation_active and runtime.conversation_shop_button.visible and runtime.conversation_persona.id == "trader_barkeep")
	var quick_start := Time.get_ticks_usec()
	runtime._submit_conversation("Can I buy one beer please?")
	assert(runtime.shop.visible and runtime.shop.pending.item_id == "beer" and not runtime.dialogue_client.waiting and inventory.quantity("beer") == 2, "Clear purchase waited for Ollama or spent without confirmation.")
	print("FAST PURCHASE CONFIRMATION: %.2fms; no Ollama request." % (float(Time.get_ticks_usec()-quick_start)/1000.0))
	runtime.shop.cancel_quote()
	runtime.shop.close()
	runtime.dialogue_client.purchase_suggestion = {"item_id": "beer", "quantity": 1}
	runtime._on_dialogue_reply(true, "Certainly, one beer.", "")
	assert(runtime.shop.visible and inventory.quantity("beer") == 2, "Dialogue did not propose a confirmation, or spent immediately.")
	if OS.get_cmdline_user_args().has("--render"):
		runtime._configure_runtime_presentation()
		for frame in 5: await process_frame
		await RenderingServer.frame_post_draw
		assert(runtime.shop.panel.get_global_rect().end.x <= 640 and runtime.shop.panel.get_global_rect().end.y <= 330, "Shop content overflowed the safe play area.")
		var image := root.get_texture().get_image()
		var image_path := ProjectSettings.globalize_path("res://docs/screenshots/trader_confirmation_ui.png")
		DirAccess.make_dir_recursive_absolute(image_path.get_base_dir())
		assert(image.save_png(image_path) == OK)
	var events := [0]
	runtime.trade_completed.connect(func(_trade): events[0] += 1)
	runtime.shop._accept()
	assert(events[0] == 1 and inventory.quantity("beer") == 3 and inventory.quantity("keks") == 85)
	assert(Service.remaining(inventory, "storyline_npc_004", pub.data.traders.storyline_npc_004.offers[0]) == 19)
	runtime.shop._accept()
	assert(events[0] == 1)
	runtime._end_conversation("Ended")
	assert(not runtime.shop.visible and runtime.shop.pending.is_empty())
	assert(runtime.has_signal("trade_completed"))
	runtime.queue_free()
	var studio = load("res://scenes/creator_studio.tscn").instantiate()
	root.add_child(studio)
	studio._load_existing_project(real_town)
	studio._show_personas_page()
	assert(is_instance_valid(studio.trader_editor) and studio.trader_editor.load_ok, "Full Creator persona page did not load traders.")
	var pub_index := -1
	for i in studio.trader_editor.npc_choice.item_count:
		if str(studio.trader_editor.npc_choice.get_item_metadata(i)) == "storyline_npc_004": pub_index = i
	assert(pub_index >= 0)
	studio.trader_editor.npc_choice.select(pub_index)
	studio.trader_editor._select_npc(pub_index)
	assert(studio.trader_editor.enabled_choice.button_pressed and studio.trader_editor.role_edit.text == "Barkeep")
	assert(studio.trader_editor.npc_choice.get_item_text(pub_index).contains("The Pub"))
	studio._show_inventory_page()
	assert(studio.trader_editor == null, "Stale trader UI survived changing sections.")
	studio.queue_free()
	editor.queue_free()
	shop.queue_free()
	adapter.queue_free()
	await process_frame
	print("TRADERS PASSED: quotes, validation, purchase, both inventories, disk reload/replacement, failure rollback, Creator stock/settings, cancel/double acceptance, model intent and Albury pub configuration.")
	quit()
