'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const assert = require('assert');
const { validateGameLore } = require('../creator-cli.js');
const output = path.join(__dirname, 'output');
fs.mkdirSync(output, { recursive: true });
const directory = fs.mkdtempSync(path.join(output, 'game-lore-cli-'));
const metadataPath = path.join(directory, 'data', 'game_lore.json');
fs.mkdirSync(path.join(directory, 'data', 'game_lore'), { recursive: true });
assert(validateGameLore(directory).passed);
fs.writeFileSync(metadataPath, JSON.stringify({ schema_version: 1, lore: {} }));
assert(validateGameLore(directory).passed);
const bytes = fs.readFileSync(path.join(__dirname, '..', '..', 'data', 'examples', 'game_lore_world_at_risk.txt'));
const sha256 = crypto.createHash('sha256').update(bytes).digest('hex');
const relative_path = `data/game_lore/${sha256}.txt`;
const metadata = { schema_version: 1, lore: { sha256, relative_path, original_filename: 'example.txt' } };
fs.writeFileSync(metadataPath, JSON.stringify(metadata));
assert(validateGameLore(directory).warnings.length === 1);
fs.writeFileSync(path.join(directory, relative_path), bytes);
assert(validateGameLore(directory).passed && validateGameLore(directory).warnings.length === 0);
fs.writeFileSync(path.join(directory, relative_path), 'Changed after upload');
assert(validateGameLore(directory).warnings[0].includes('changed'));
fs.writeFileSync(path.join(directory, relative_path), Buffer.from([0, 255, 1]));
assert(validateGameLore(directory).warnings[0].includes('UTF-8'));
fs.writeFileSync(path.join(directory, relative_path), 'x'.repeat(65537));
assert(validateGameLore(directory).warnings[0].includes('64 KB'));
metadata.lore.relative_path = '../escape.txt';
fs.writeFileSync(metadataPath, JSON.stringify(metadata));
assert(!validateGameLore(directory).passed);
fs.writeFileSync(metadataPath, 'invalid json');
assert(!validateGameLore(directory).passed);
console.log('GAME LORE CLI PASSED: optional/empty, copy/hash, missing/oversized/binary warnings, unsafe/corrupt metadata rejection.');
