'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const cli = require('../creator-cli');
const directory = fs.mkdtempSync(path.join(__dirname, 'output', 'tree-cli-'));
fs.mkdirSync(path.join(directory, 'data'));
fs.writeFileSync(path.join(directory, 'town.json'), '{}');
assert.equal(cli.getTreeSettings({town: directory}).data.tree_style, 'mapped');
assert.equal(cli.setTreeStyle({town: directory, style: 'eucalypt'}).data.tree_style, 'eucalypt');
const file = path.join(directory, 'data/environment_settings.json');
const original = fs.readFileSync(file, 'utf8');
assert.throws(() => cli.setTreeStyle({town: directory, style: '../unsafe'}));
assert.equal(fs.readFileSync(file, 'utf8'), original);
const data = JSON.parse(original);
data.custom_trees = [{id: 'custom_' + 'a'.repeat(64), sha256: 'a'.repeat(64), name: 'Missing tree', relative_path: 'assets/environment/trees/' + 'a'.repeat(64) + '.png'}];
fs.writeFileSync(file, JSON.stringify(data));
assert.equal(cli.validateEnvironmentSettings(directory).warnings.length, 1);
data.custom_trees[0].relative_path = '../outside.png';
fs.writeFileSync(file, JSON.stringify(data));
assert.equal(cli.validateEnvironmentSettings(directory).passed, false);
assert.throws(() => cli.setTreeStyle({town: directory, style: 'mapped'}));
const fixture = cli.parseOsmFiles([path.join(__dirname, 'fixtures/environment_detail.osm')]);
assert.equal(fixture.statistics.individual_trees, 3);
assert(fixture.features.some(item => item.kind === 'tree_row'));
assert(!fixture.features.some(item => item.id === 'node:13'));
console.log('TREE CLI PASSED: defaults, gum selection, invalid style/path preservation, missing-copy warning and OSM ground trees/rows.');
