'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const {validateRig,PARTS,VIEWS}=require('../npc_creations/validate-npc-rig');
const {validateNpcCreations}=require('../npc_creations/validate-npc-creations');
const directory=path.resolve(process.argv[2]);
const catalog=JSON.parse(fs.readFileSync(path.join(directory,'data/npc_creations.json'),'utf8'));
const rig=catalog.creations[0].rig;
let checks=0;
function check(ok,message){assert.ok(ok,message);checks++;}
function reject(edit){const draft=structuredClone(rig);edit(draft);check(!validateRig(draft).ok,'Invalid rig accepted');}
check(validateNpcCreations(catalog,directory).ok,'Godot-saved skeleton not valid in CLI');
check(validateRig(rig).paths.length===40,'Expected forty starter pieces');
for(const view of VIEWS)for(const part of PARTS)check(fs.existsSync(path.join(directory,rig.views[view].parts[part].image)),'Missing starter');
for(const value of [null,[],{},1])check(!validateRig(value).ok,'Invalid object accepted');
reject(r=>r.enabled='yes');reject(r=>r.version=2);
reject(r=>r.walk_cycles_per_second=4);reject(r=>r.stride_degrees=-1);
reject(r=>r.views.front.parts.head.image='assets/npcs/../outside.png');
reject(r=>r.views.front.parts.head.image='C:/outside.png');
reject(r=>r.views.front.parts.head.image='assets/npcs/script.gd');
reject(r=>r.views.front.parts.head.image='');
reject(r=>delete r.views.front);reject(r=>delete r.views.left.parts.head);
reject(r=>r.views.front.parts.head.position=[NaN,0]);
reject(r=>r.views.front.parts.head.size=[0,42]);
reject(r=>r.views.front.parts.head.pivot=[.5,2]);
reject(r=>r.views.front.parts.head.z_index=.5);
reject(r=>r.views.front.parts.head.flip_h=1);
const fallback=structuredClone(rig);fallback.views.back.parts.head.image='';
check(validateRig(fallback).ok,'Incomplete optional images should fall back');
const disabled=structuredClone(catalog);disabled.creations[0].rig.enabled=false;
check(!validateNpcCreations(disabled,directory).ok,'Frame mode without front art accepted');
const identity=catalog.creations[0];
const reference={actor_kind:'npc',appearance:{mode:'custom_creation',template_id:identity.id,npc_asset:'creation_'+identity.id,gender:identity.gender,age_group:identity.age_group,skin_tone_group:identity.skin_tone_group}};
check(validateNpcCreations(catalog,directory,[reference]).ok,'Rig placement rejected');
reference.appearance.gender=identity.gender==='man'?'woman':'man';check(!validateNpcCreations(catalog,directory,[reference]).ok,'Mismatched placement accepted');
const schema=JSON.parse(fs.readFileSync(path.join(__dirname,'../../schemas/npc_creations.schema.json'),'utf8'));
check(schema.$defs.rigView.properties.parts.required.length===10,'Schema misses joints');
console.log(`NODE NPC RIG: ${checks} checks, 0 failures`);
